Name: kafka
Brokers:
  - 127.0.0.1:9092
  - 127.0.0.1:9092
  - 127.0.0.1:9092
Group: kafka
Topic: kafka
Offset: first
Consumers: 1

Telemetry:
  Name: kq
  Endpoint: http://localhost:14268/api/traces
  Sampler: 1.0
  Natcher: jaeger